version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: exam_generator_db
    environment:
      POSTGRES_DB: exam_generator
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - exam_generator_network

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: exam_generator_backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/exam_generator
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - exam_generator_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: exam_generator_frontend
    environment:
      - REACT_APP_API_URL=http://localhost:8080/api
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - exam_generator_network

networks:
  exam_generator_network:
    driver: bridge

volumes:
  postgres_data: 